/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contributors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Contributors */
        get: operations["read_contributors_contributors_get"];
        put?: never;
        /** Create Contributor */
        post: operations["create_contributor_contributors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributors/{contributor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Contributor */
        get: operations["read_contributor_contributors__contributor_id__get"];
        /** Update Contributor */
        put: operations["update_contributor_contributors__contributor_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Contributions */
        get: operations["read_contributions_contributions_get"];
        put?: never;
        /** Create Contribution */
        post: operations["create_contribution_contributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributions/{contribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Contribution */
        get: operations["read_contribution_contributions__contribution_id__get"];
        /** Update Contribution */
        put: operations["update_contribution_contributions__contribution_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Tags */
        get: operations["read_tags_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Tag */
        get: operations["read_tag_tags__tag_id__get"];
        /** Update Tag */
        put: operations["update_tag_tags__tag_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Reviews */
        get: operations["read_reviews_reviews_get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Review */
        get: operations["read_review_reviews__review_id__get"];
        /** Update Review */
        put: operations["update_review_reviews__review_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContributionCreate */
        ContributionCreate: {
            /** Title */
            title: string;
            /** Short Title */
            short_title: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Links */
            links: components["schemas"]["ContributionLinks"][];
            /** Description */
            description: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Contributors */
            contributors: number[];
            /** Tags */
            tags: number[];
        };
        /** ContributionLinks */
        ContributionLinks: {
            /** Description */
            description: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ContributionPublicWithAttributesShortPublic */
        ContributionPublicWithAttributesShortPublic: {
            /** Title */
            title: string;
            /** Short Title */
            short_title: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Links */
            links: components["schemas"]["ContributionLinks"][];
            /** Description */
            description: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Contributors
             * @default []
             */
            contributors: components["schemas"]["ContributorShort"][];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagPublic"][];
            /**
             * Reviews
             * @default []
             */
            reviews: components["schemas"]["ReviewPublic"][];
        };
        /** ContributionUpdate */
        ContributionUpdate: {
            /** Title */
            title: string;
            /** Short Title */
            short_title: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Links */
            links: components["schemas"]["ContributionLinks"][];
            /** Description */
            description: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Contributors */
            contributors: number[];
            /** Tags */
            tags: number[];
        };
        /** Contributor */
        Contributor: {
            /** Local Handle */
            local_handle: string;
            /** Display Name */
            display_name: string;
            /** Discord Handle */
            discord_handle?: string | null;
            /** Github Account */
            github_account?: string | null;
            /** Discourse Account */
            discourse_account?: string | null;
            /** Wiki Account */
            wiki_account?: string | null;
            /** Website */
            website?: string | null;
            /** Extra Info */
            extra_info?: {
                [key: string]: string | undefined;
            } | null;
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ContributorShort */
        ContributorShort: {
            /** Id */
            id: number;
            /** Local Handle */
            local_handle: string;
        };
        /** ContributorUpsert */
        ContributorUpsert: {
            /** Local Handle */
            local_handle: string;
            /** Display Name */
            display_name: string;
            /** Discord Handle */
            discord_handle?: string | null;
            /** Github Account */
            github_account?: string | null;
            /** Discourse Account */
            discourse_account?: string | null;
            /** Wiki Account */
            wiki_account?: string | null;
            /** Website */
            website?: string | null;
            /** Extra Info */
            extra_info?: {
                [key: string]: string | undefined;
            } | null;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ReviewCreate */
        ReviewCreate: {
            /** Link */
            link: string;
            /** Notes */
            notes: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Contribution Id */
            contribution_id: number;
            /** Reviewers */
            reviewers: number[];
        };
        /** ReviewPublic */
        ReviewPublic: {
            /** Link */
            link: string;
            /** Notes */
            notes: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id: number;
            /** Contribution Id */
            contribution_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Reviewers
             * @default []
             */
            reviewers: components["schemas"]["ContributorShort"][];
        };
        /** Tag */
        Tag: {
            /** Display Name */
            display_name: string;
            /** Color */
            color: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** TagCreate */
        TagCreate: {
            /** Display Name */
            display_name: string;
            /** Color */
            color: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** TagPublic */
        TagPublic: {
            /** Display Name */
            display_name: string;
            /** Color */
            color: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id: number;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Display Name */
            display_name: string;
            /** Color */
            color: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_contributors_contributors_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contributor_contributors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributorUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_contributor_contributors__contributor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contributor_contributors__contributor_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributorUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contributor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_contributions_contributions_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionPublicWithAttributesShortPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contribution_contributions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionPublicWithAttributesShortPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_contribution_contributions__contribution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contribution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionPublicWithAttributesShortPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contribution_contributions__contribution_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contribution_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionPublicWithAttributesShortPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tags_tags_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tag_tags__tag_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_tags__tag_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_reviews_reviews_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_review_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_review_reviews__review_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
